package se.melsom.warehouse.event;

public enum EventType {
	ITEM_LIST_RELOADED,
	ITEM_LIST_MODIFIED,
	STOCK_LOCATIONS_RELOADED,
	STOCK_LOCATIONS_MODIFIED,
	INVENTORY_UPDATED, 
	ORGANIZATIONAL_UNITS_RELOADED,
	ORGANIZATIONAL_UNITS_UPDATED,
	HOLDINGS_RELOADED,
	OLDINGS_UPDATED
}
